config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] 
  resources :welcome, only: [:index]
  resources :chicks, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
  	resources :comments, only: [:create, :new, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/chicks/:id/like', to: 'chicks#like', as: :like
end

app/models/chick.rb
class Chick < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :chick
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :chicks
	has_many :comments
	validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
  	redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end
end

app/controllers/chicks_controller.rb
class ChicksController < ApplicationController
	before_action :authorize, except: [:index, :show]

	def index
		@chicks = Chick.all
		# @chicks = @chicks.paginate(:page => params[:page], :per_page => 5)
	end

	def create
	  chick = Chick.new(chick_params)
	  chick.user = current_user
	  if chick.save
	    flash[:notice] = "you posted a Bad-Ass Chick!"
	    redirect_to root_path
	  else
	    render 'new'
	  end
	end

	def new
		@chick = Chick.new
	end

	def show
		@chick = Chick.find(params[:id])
	end


	def edit
		@chick = Chick.find(params[:id])
		render 'new'
	end

	def update
		@chick = Chick.find(params[:id])
		if @chick.update(chick_params)
			redirect_to @chick
		# redirect_to chicks_path, :action => 'show', :id => @chick_id
		else
			render	'edit'
		end
	end

	def like
		chick = Chick.find(params[:id])
		chick.likes += 1
		chick.save
		redirect_to chicks_path(anchor: chick.name.parameterize)
		# redirect_to chicks_path
	end

	def destroy
		@chick = Chick.find(params[:id])
		@chick.destroy
		redirect_to chicks_path
	end

	private

	def chick_params
		params.require(:chick).permit(:name, :image_uri, :category, :text)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def new
		@comment = Comment.new
		@chick = Chick.find(params[:chick_id])
	end

	def create
		@chick = Chick.find(params[:chick_id])
		@comment = @chick.comments.build(comment_params)
		@comment.user = current_user

		if @comment.save
			flash[:notice] = "Comment added!"
			redirect_to chicks_path(anchor: @chick.name.parameterize)
		else
			render 'new'
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to chicks_path(@chick)
	end

	private
	def comment_params
		params.require(:comment).permit(:body, :user, :chick)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: 'Logged in!'
		else
			flash.now.alert = 'Invalid login credentials - try again'
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: 'Logged out!'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate, only: [:show, :edit, :update]
	before_action :authorize, only: [:show, :edit, :update]


def new
	@user = User.new
end

def create
	@user = User.new(user_params)
	if @user.save
		flash[:notice] = "You have successfully signed up!"
		session[:user_id] = @user.id #login
		redirect_to user_path(@user)
	else
		render :new
	end
end

def show
end

def edit
	@user = User.find(params[:id])
end

def update
	@user = User.find(params[:id])
	if @user.update(user_params)
		redirect_to user_path(@user)
	else
		render :edit
	end
end

	def destroy
		@chick.destroy
		redirect_to user_path(current_user)
	end

private

	def user_params
		params.require(:user).permit(:email, :handle, :profile_image_uri, :password, :password_confirmation)
	end

	def authenticate
		redirect_to new_session_path, alert: 'You must be logged in the continue!' if current_user.nil?
	end

	def authorize
		@user = User.find(params[:id])
		redirect_to root_path if @user != current_user
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chicks_helper.rb
module ChicksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chicks/_form.html.erb
<%= form_for @chick do |f| %>
  <% if @chick.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @chick.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="imageField" id="firstblock">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="textField">
    <%= f.label :image_uri %>
    <%= f.text_field :image_uri %>
  </div>
  <div class="textField">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class="textField">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="createChick"><%= f.submit %></div>
<% end %>

app/views/chicks/index.html.erb
<div class="chicks-container">
	<div class="chicks-feed">

		<h1>Bad-Ass Chicks List</h1>

		<% @chicks.each do |chick| %>
		    <div id="<%= chick.name.parameterize %>">
				<h2><%= chick.name %></h2>
				<%= image_tag((chick.image_uri), :class => "images") %>
			
				<h3><%= chick.category %></h3>
				<p><%= chick.text %></p>
			
				<h4><%= chick.likes %> likes </h4>
				<span class="likes">
					<%= link_to(like_path(:id => chick.id)) do %>
				   		<span class="glyphicon glyphicon-heart btn btn-default"></span>
				  	<% end %>
				</span>

				<button class="btn btn-default"><%= link_to "edit profile", edit_chick_path(chick) %></button>
				
				<% if current_user %>
					<button class="btn btn-default"><%= link_to "comment", new_chick_comment_path(chick) %></button>
					<% if current_user.id == chick.user_id %>
						<button class="btn btn-default"><%= link_to "delete profile", chick, method: :delete, data: { confirm: 'Are you sure?'} %></button>
					<% end %>
				<% end %>
				
				<% chick.comments.each do |ch| %>
					<%= ch.body %>
					<button class="btn btn-default"><%= link_to "X", chick_comment_path(chick, ch), method: :delete %></button>
				<% end %>
			</div>
		<% end %>
	
	</div>
</div>

app/views/chicks/new.html.erb
<%= render 'form' %>

app/views/chicks/show.html.erb
<h1><%= @chick.name %></h1>
	<%= image_tag((@chick.image_uri), :id => 'chick_id', :class => 'chick_class') %>
	<h3><%= @chick.category %></h3>
	<p><%= @chick.text %></p>
	
	
	<button class="btn btn-default"><%= link_to "comment", new_chick_comment_path(@chick) %></button>

app/views/comments/_form.html.erb
</ol>
<h3>Comments:</h3>
<%= form_for [@chick, @comment] do |f| %>
  <div class="field">
    <%= f.label "New Comment" %>
    <%= f.text_field :body %>
    <% @comment.chick = @chick %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>
<ul>

app/views/comments/new.html.erb
<h1>Leave a comment</h1>

</ol>
<h3>Comments:</h3>
<%= form_for [@chick, @comment] do |f| %>
  <div class="field">
    <%= f.label "New Comment" %>
    <%= f.text_field :body %>
    <% @comment.chick = @chick %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>
<ul>

app/views/edits/_form.html.erb
<%= form_for @chick do |f| %>
  <% if @chick.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @chick.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="imageField" id="firstblock">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="textField">
    <%= f.label :image_uri %>
    <%= f.text_field :image_uri %>
  </div>
  <div class="textField">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class="textField">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="createChick"><%= f.submit %></div>
<% end %>

app/views/edits/edit.html.erb
<%= form_for @chick do |f| %>
  <% if @chick.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @chick.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="imageField" id="firstblock">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="textField">
    <%= f.label :image_uri %>
    <%= f.text_field :image_uri %>
  </div>
  <div class="textField">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class="textField">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="createChick"><%= f.submit %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BadassChickDatabase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    
   <div class="container">
    
    # <%= link_to "BCDB", root_path, class: "logo" %>
    
    
    <div class="navBar">
      <span class="navLinks"><%= link_to "Add Profile", new_chick_path %></span>
      <span class="navLinks"><%= link_to "See All", chicks_path %></span>
    </div>

    
    
    <p class="logins">
      <% if current_user %>
      <%= link_to "Logged In! #{current_user.name}", user_path(current_user) %>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to 'Logout', session_path('dummy'), method: :delete %>
      <% else %>
      <%= link_to 'Login', login_path %>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to 'Sign Up', new_user_path %>
      <% end %>
    </p>
    
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :image_uri, "Profile Image Link" %>
    <%= f.text_field :image_uri %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/edit.html.erb
<h1>Update your account details</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Register a new account</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %></h1>

<p><%= @user.email %></p>
<%= image_tag @user.image_uri, width: "300px" %>

<%= button_to "Edit account", edit_user_path(@user), method: :get %>

app/views/welcome/index.html.erb
<div class="content text-center">
<header>

	
<h1>Bad-Ass Chicks Database</h1>
<h4>Add profiles and comment on your favorite bad bitches</h4>
</header>

	<div class="frontPageDiv">
	<img class="frontPage" src="https://bullybloggers.files.wordpress.com/2010/08/lisbeth-salander-31.jpg">
	<img class="frontPage" src="http://www.altfg.com/film/wp-content/uploads/images/2015/05/mad-max-fury-road-charlize-theron.jpg">
	<img class="frontPage" src="http://1513f43de1df8b08e16c-d8d6213b156ba3a73e333057f5885fa8.r32.cf1.rackcdn.com/1280-xfsn53hqa11eqs7hyaefy4z2d7qxxe6qwktk49fe.jpg">
	<img class="frontPage" src="https://timedotcom.files.wordpress.com/2000/04/ruth-bader-ginsburg-time-100-2015-icons.jpg?quality=65&strip=color&w=814">
		
	</div>
</div>